# Dependencies
highlighter:   rouge   #pygments

gems: 
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Xianfeng Li
tagline:          'Too little time'
description:      'Bioinformatics PhD @Zhong-Sheng Sun Lab'
url:              http://xflicsu.github.io
baseurl:          /

author:
  name:           'Xianfeng Li'
  url:            https://www.researchgate.net/profile/Xianfeng_Li4

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/xflicsu/xflicsu.github.io

theme: jekyll-theme-dinky
